name: uncluster

channels:
  - astropy
  - asmeurer

dependencies:
  - astropy
  - numpy
  - matplotlib
  - cython
  - scipy
  - h5py
  - gsl=1.16
  - pip
  - pip:
    - git+https://github.com/adrn/gala.git
    - cythongsl
    - schwimmbad
